pub mod ancestry;
pub mod twentythree;
pub mod vcf;

use serde::{Deserialize, Serialize};

/// A single parsed SNP from any file format.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ParsedSnp {
    pub rsid: String,
    pub chromosome: String,
    pub position: i64,
    pub genotype: String,
}

/// Result of parsing a raw DNA data file.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ParseResult {
    pub snps: Vec<ParsedSnp>,
    pub format: String,
    pub build: Option<String>,
    pub total_lines: usize,
    pub skipped_lines: usize,
}

/// Detect the file format by inspecting header content.
/// Returns one of: "23andme_v5", "23andme_v3", "ancestry", "vcf", "unknown".
pub fn detect_format(content: &str) -> String {
    // Take the first few KB for detection
    let header: String = content.chars().take(4096).collect();

    if header.starts_with("##fileformat=VCF") {
        return "vcf".to_string();
    }

    // AncestryDNA files contain "AncestryDNA" in the header
    if header.contains("AncestryDNA") {
        return "ancestry".to_string();
    }

    // 23andMe v5 files typically have a header line with column names after comment lines
    if header.contains("23andMe") || header.contains("# rsid") {
        // v5 has the explicit header line "# rsid\tchromosome\tposition\tgenotype"
        // v3 may lack that or have different formatting
        if header.contains("# rsid\tchromosome\tposition\tgenotype")
            || header.contains("# This data has been generated by 23andMe")
        {
            // Distinguish v5 vs v3 by looking for specific v5 markers
            // v5 files often mention "build 37" and have more SNPs
            if header.contains("v5") || header.contains("build 37") || header.contains("# rsid\t") {
                return "23andme_v5".to_string();
            }
        }

        return "23andme_v3".to_string();
    }

    // Fallback: if lines look like tab-separated with rsid, chr, pos, genotype
    for line in header.lines() {
        let line = line.trim();
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let parts: Vec<&str> = line.split('\t').collect();
        if parts.len() >= 4 && parts[0].starts_with("rs") {
            return "23andme_v3".to_string();
        }
        if parts.len() >= 5 && parts[0].starts_with("rs") {
            return "ancestry".to_string();
        }
        break;
    }

    "unknown".to_string()
}
